### ISSUE TITLE
Can't run rms using Custom docker image

### ISSUE THREAD

**Issue by rajatjain4949** [Azure/azure-iot-pcs-remote-monitoring-dotnet#100]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Trying to create a customized image of device simulation using dockerfile present in ./device-simulation/scripts/docker using command docker build .
facing following error.

D:\azure-iot-pcs-remote-monitoring-dotnet\device-simulation\scripts\docker>docker build .
Sending build context to Docker daemon  17.41kB
Step 1/12 : FROM microsoft/dotnet:2.0.3-runtime-jessie
 ---> ae7549202f75
Step 2/12 : MAINTAINER Devis Lucato (https://github.com/dluc)
 ---> Using cache
 ---> 3ac3078a2baf
Step 3/12 : LABEL Tags="Azure,IoT,Solutions,Simulation,.NET"
 ---> Using cache
 ---> d8ff7253ea11
Step 4/12 : ARG user=pcsuser
 ---> Using cache
 ---> 8b375c5bac2e
Step 5/12 : RUN useradd -m -s /bin/bash -U $user
 ---> Using cache
 ---> ba742e33703e
Step 6/12 : COPY . /app/
 ---> af67933c0c40
Step 7/12 : RUN chown -R $user.$user /app
 ---> Running in 9c7034410ae6
Removing intermediate container 9c7034410ae6
 ---> a211c60d06f4
Step 8/12 : WORKDIR /app
Removing intermediate container da1f6e17ec06
 ---> 1899efc016b3
Step 9/12 : RUN     chmod ugo+x /app/run.sh &&     rm -f /app/Dockerfile /app/.dockerignore
 ---> Running in fef9c1c26903
chmod: cannot access '/app/run.sh': No such file or directory
The command '/bin/sh -c chmod ugo+x /app/run.sh &&     rm -f /app/Dockerfile /app/.dockerignore' returned a non-zero code: 1

Same thing is happening for asa-manager also.

# Steps to reproduce 
1. Goto directory- ./device-simulation/scripts/docker
2. In cmd, rum docker build .

# Context and Environment
* Operating System: ... Windows 10

**Comment by ppathan** [comment]
That is not how we do docker builds. There is a build script inside of the folder that needs to be run for building docker images. So just run `build` or `build.cmd` from the `~scripts\docker` folder.

**Comment by rajatjain4949** [comment]
@ppathan Thanks a lot.
