### ISSUE TITLE
Remove temporary solution used to flag external requests

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-pcs-remote-monitoring-dotnet#11]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Enhancement

# Description
Revert https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/pull/10

See also https://github.com/Azure/pcs-auth-dotnet/issues/18

**Comment by ppathan** [comment]
Moved to TFS
