### ISSUE TITLE
IP addresses of IoT Hubs

### ISSUE THREAD

**Issue by kidproquo** [Azure/azure-iot-pcs-remote-monitoring-dotnet#114]
We see that all the IoT Hubs under Standard deployment resolve to the same IP address.  See below:

```
PSamuel@SLB-F4Z42G2` C:\Users\psamuel
> ping wbocm-hub.azure-devices.net

Pinging ihsu-prod-dm-001.cloudapp.net [13.89.231.149] with 32 bytes of data:
Control-C
^C
PSamuel@SLB-F4Z42G2 C:\Users\psamuel
> ping nwll6-hub.azure-devices.net

Pinging ihsu-prod-dm-001.cloudapp.net [13.89.231.149] with 32 bytes of data:
Control-C
^C
PSamuel@SLB-F4Z42G2 C:\Users\psamuel
> ping 2mm74-hub.azure-devices.net

Pinging ihsu-prod-dm-001.cloudapp.net [13.89.231.149] with 32 bytes of data:
Control-C
`^C`
```

Is this by design? 

Will it always be the same IP address? We need to create firewall rules to allow access to the IoT Hubs from the Edge device. If the IoT Hubs will always resolve to the same IP address then can we create just one rule for all IoT Hubs?

**Comment by giyeh** [comment]
@ppathan to help take a look

**Comment by ppathan** [comment]
Hi @kidproquo Can you explain your scenario in little bit detail. Why do you need to create a firewall and what are you trying to achieve? Also when you say standard is it RMv2 standard deployment or IoT Hub Standard sku?

**Comment by kidproquo** [comment]
@ppathan any update? Do you need any more information?

**Comment by rezasherafat** [comment]
@kidproquo, your IoT Hub's IP address _may_ change - this happens rarely and mainly after a regional failover. If you are allowing traffic only to specific addresses you need to ensure you can change the firewall rules if IoT Hub's IP changes.

**Comment by rezasherafat** [comment]
Also, note that typically only the Edge Hub and Edge Agent will need direct connectivity to IoT Hub.

A module _may_ connect too, but that is not standard practice.

**Comment by ppathan** [comment]
Questions answered hence closing the issue.

**Comment by jlian** [comment]
To folks finding this now: we published a doc on this subject https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-understand-ip-address
