### ISSUE TITLE
Cannit deploy locally

### ISSUE THREAD

**Issue by gknowd** [Azure/azure-iot-pcs-remote-monitoring-dotnet#115]
# Type of issue 
- [ x] Bug
- [ ] New feature
- [ ] Improvement

# Description 

When running the docker-compose up command, I get a failure when it gets to the reverse proxy with a b'Drive has not been shared' Am I missing a configuration somewhere?

# Screenshot 
$ docker-compose up
local_storageadapter_1 is up-to-date
local_auth_1 is up-to-date
local_telemetry_1 is up-to-date
local_devicesimulation_1 is up-to-date
local_iothubmanager_1 is up-to-date
local_config_1 is up-to-date
local_webui_1 is up-to-date
local_asamanager_1 is up-to-date
Creating local_reverseproxy_1 ... error

ERROR: for local_reverseproxy_1  Cannot create container for service reverseproxy: b'Drive has not been shared'

ERROR: for reverseproxy  Cannot create container for service reverseproxy: b'Drive has not been shared'
ERROR: Encountered errors while bringing up the project.
# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by ppathan** [comment]
Can you confirm if the drive is being shared or not? Have you tried unsharing and sharing again?

**Comment by andrejpk** [comment]
When I ran into this error, checking the drive of my local repo in Docker settings fixed this:
![image](https://user-images.githubusercontent.com/1774478/43530738-4da3741c-957c-11e8-9ed1-c747a7fcf517.png)
