### ISSUE TITLE
Couldn't find MSIOT_Hub_sample_device_lab_2.sln solution  file in lab2

### ISSUE THREAD

**Issue by anwarabidali** [Azure/azure-iot-pcs-remote-monitoring-dotnet#121]
# Type of issue 
- [x] Bug

# Description 
...1.	Couldn't file  MSIOT_Hub_sample_device_lab_2.sln solution file
# Screenshot 
Couldn't find MSIOT_Hub_sample_device_lab_2.sln solution 

![untitled](https://user-images.githubusercontent.com/31575027/44488844-73dd4480-a677-11e8-94ef-8490ef081738.png)

# Steps to reproduce 
1. Open Lab 2 : Customizing the RM solution accelerator
2. Goto step 1.1  Open the MSIOT_Hub_sample_device_lab_2.sln solution. This is located in the Lab2\SampleDevice directory.
3. It doesn't provide location, where project file can be downloaded. It is not in PPE lan manual zip file.

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by hegate** [comment]
@asdonald this seems to be a typo in the latest labs from Ranga, could you take a look?

**Comment by asdonald** [comment]
@anwarabidali This is not part of this repository. This folder does not get shipped with the Remote Monitoring open source repo. 

MSIOT_Hub_sample_device_lab_2.sln should be a zip folder that comes with all the Labs and Modules for IoT PPE training only.
@rangv as FYI.

**Comment by asdonald** [comment]
@hegate This issue has been resolved. Moving to closed.
