### ISSUE TITLE
error while rendering map in remote monitoring app

### ISSUE THREAD

**Issue by anwarabidali** [Azure/azure-iot-pcs-remote-monitoring-dotnet#122]
# Type of issue 
- [X ] Bug
- [ ] New feature
- [ ] Improvement

# Description 
...error while rendering map in remote monitoring app
# Screenshot 
![untitled2](https://user-images.githubusercontent.com/31575027/44488948-b9017680-a677-11e8-87de-88056abda14d.png)

# Steps to reproduce 
1. Open Lab 1 - Introduction to Azure IoT and RM
2. Goto: Monitoring section 
3. Goto: Choose the devices to display. Choose the built-in Trucks filter in the filter drop-down to change the devices displayed on the Dashboard page.
4. Map visual is not loaded. Error message "error while rendering map" comes

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by hegate** [comment]
@ppathan  can you take a look at this error?

**Comment by isaac73** [comment]
@anwarabidali couldn't repo this. Which region is your deployment in?

**Comment by isaac73** [comment]
Are you trying to deploy in one of these unsupported countries?
Argentina
China
India
Morocco
Pakistan
South Korea

**Comment by isaac73** [comment]
Closing this issue, since this deployment was done in south-east-Asia and since AzureMaps is not supported there.

**Comment by asdonald** [comment]
@isaac73 We need to check for error and then display that maps isn't available in their region.

**Comment by asdonald** [comment]
@isaac73 Azure Maps as a service is not available in some countries around the world. It doesn't matter where you make the deployment, rather, its where you are physically viewing the browser that matters. For example, if you make a deployment in EastUS but open that deployment in India, you will not see the map.

**Comment by isaac73** [comment]
@asdonald I'm currently into Edge work. I will be looking at this in about 2 weeks. Is that ok?

**Comment by asdonald** [comment]
@asdonald To go to the WebUI and link the duplicate issue here.

**Comment by mechaffin** [comment]
@anwarabidali Can you repro this issue again? Then please send us the error written to the console log in the dev tools so we can see which error is actually being encountered.
