### ISSUE TITLE
Version info in settings panel shows latest release

### ISSUE THREAD

**Issue by kidproquo** [Azure/azure-iot-pcs-remote-monitoring-dotnet#126]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
The version info in the settings panel simply points to the latest release and its release notes.

# Screenshot 
![image](https://user-images.githubusercontent.com/410966/45368744-f5a2fc80-b5a9-11e8-919c-16dcab18afc0.png)

# Steps to reproduce 
1. Click the settings gear icon
2. Version info is shown on the top of the panel

# Expected behavior 
The actual version of RMS should be displayed and the link should point to that version's release notes.

# Current behavior 
The version info in the settings panel simply points to the latest release and its release notes.

**Comment by asdonald** [comment]
Ashley to create a new deployment and verify.

**Comment by ppathan** [comment]
I tried out with latest deployment and it showing the latest release notes and link. Let us know if this is still the issue.
![image](https://user-images.githubusercontent.com/16170750/45564187-8543e780-b804-11e8-8ff4-c5867fdc50f8.png)

**Comment by kidproquo** [comment]
@ppathan, this is not correct. We have not upgraded to the latest version and we see 1.0.2 as the version! The code just looks up the latest release on GitHub and shows that release's info.

![image](https://user-images.githubusercontent.com/410966/45567408-5f780c00-b81f-11e8-80ba-2ec2730c7a06.png)

**Comment by ppathan** [comment]
@kidproquo Now I get it. The original screenshot was showing old release version so we thought other way :). Yeah this is a known issue. Will reopen.

**Comment by asdonald** [comment]
@isaac73 Can you please look into this bug

**Comment by ppathan** [comment]
Fixed. But will only work with the latest deployment.
