### ISSUE TITLE
ERROR: for reverseproxy  Cannot start service reverseproxy: OCI runtime create failed: container_linux.go:348

### ISSUE THREAD

**Issue by sergaz-msft** [Azure/azure-iot-pcs-remote-monitoring-dotnet#127]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Following [this ](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) How-to guide.

After the step `docker-compose up` I get the following error:

> local_storageadapter_1 is up-to-date
> local_auth_1 is up-to-date
> local_devicesimulation_1 is up-to-date
> Starting local_telemetry_1 ...
> Starting local_telemetry_1 ... done
> local_config_1 is up-to-date
> local_asamanager_1 is up-to-date
> local_webui_1 is up-to-date
> Starting local_reverseproxy_1 ... error
> 
> ERROR: for local_reverseproxy_1  Cannot start service reverseproxy: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/d/cases/180912-gh-andrepodnozov-14679/azure-iot-pcs-remote-monitoring-dotnet/scripts/local/config/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/ff9a12b5eaf98add98c7fbfa22fdabb53a1e669a336b6ecd4b582b9e4581cf1d/merged\\\" at \\\"/var/lib/docker/overlay2/ff9a12b5eaf98add98c7fbfa22fdabb53a1e669a336b6ecd4b582b9e4581cf1d/merged/app/config/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> 
> ERROR: for reverseproxy  Cannot start service reverseproxy: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/d/cases/180912-gh-andrepodnozov-14679/azure-iot-pcs-remote-monitoring-dotnet/scripts/local/config/nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/ff9a12b5eaf98add98c7fbfa22fdabb53a1e669a336b6ecd4b582b9e4581cf1d/merged\\\" at \\\"/var/lib/docker/overlay2/ff9a12b5eaf98add98c7fbfa22fdabb53a1e669a336b6ecd4b582b9e4581cf1d/merged/app/config/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
> ERROR: Encountered errors while bringing up the project.

# Context and Environment
* Operating System: Windows 10
* GitHub branch: master
* .NET Runtime: `dotnet --version` **2.1.202**

**Comment by asdonald** [comment]
@sergaz-msft There is a doc update that needs to happen. We have simplified local deployment. The following link should help you: 

https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/blob/master/docs/LOCAL_DEPLOYMENT.md

@sushilraje  can help if you run into any issues.

**Comment by sergaz-msft** [comment]
Thank you @asdonald ! Can you also answer to customer on this issue: https://github.com/MicrosoftDocs/azure-docs/issues/14679 ?

Will give it a try asap.

**Comment by asdonald** [comment]
@sergaz-msft Closing as fixed in master. Please re-open if you are still seeing issue.
