### ISSUE TITLE
Manual steps to create azure resources for basic / standard setup

### ISSUE THREAD

**Issue by developersenakim** [Azure/azure-iot-pcs-remote-monitoring-dotnet#132]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description 
Documentation on how to manually setup the basic/ standard version of IoT suite.
 
# Screenshot 
Example : https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Manual-steps-to-create-azure-resources-for-local-setup

**Comment by developersenakim** [comment]
The example shows how to set the local setup in azure portal. For advanced customization, documentation on how to set up basic/ standard version on hub will really help.

**Comment by asdonald** [comment]
@developersenakim Can you please clarify what is missing from the documentation? We recommend deploying these resources using the Arm templates and pcs cli or through iot suite (webui) this will automatically create those resources for you. 

If you would like to deploy them manually, you can look at the Arm template in this: https://github.com/Azure/pcs-cli and deploy them each manually from what we do. 

Is there something that the CLI isn't doing for you? We usually recommend using the pcs cli and just modifying the arm template to fit your needs if you need to make changes.

**Comment by developersenakim** [comment]
when i am using pcs-cli it kinda automatically all deploying for the user. I wanted to down grade - or downsized some servers or change the storage type.

I think the pcs-cli link would help thanks.
