### ISSUE TITLE
New Rule Device Group Issue

### ISSUE THREAD

**Issue by rangv** [Azure/azure-iot-pcs-remote-monitoring-dotnet#133]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 

When creating a new rule and applying device group, devices from all device groups are being selected. 
![18rule](https://user-images.githubusercontent.com/17085664/45927246-0aa25880-bee5-11e8-918b-471b7d893f0b.png)
![19rulelist](https://user-images.githubusercontent.com/17085664/45927247-0fffa300-bee5-11e8-9380-2ee876a7ef34.png)

# Screenshot 

# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by asdonald** [comment]
@rangv A device group with no condition will select "all".
