### ISSUE TITLE
Update the wiki docs on GitHub for RM

### ISSUE THREAD

**Issue by VidNa** [Azure/azure-iot-pcs-remote-monitoring-dotnet#134]
# Type of issue 
- [ x] Bug
- [ ] New feature
- [ ] Improvement
# Description 
Customer has reported the following docs as outdated. 
- Internal services - https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Internal-services
- Public facing services - https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Public-facing-services
- Developer Reference Guide - https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Troubleshooting-Guide
- Infrastructure https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Infrastructure.

**Comment by ppathan** [comment]
Fixed
