### ISSUE TITLE
Deploying via CLI using West US 2 fails

### ISSUE THREAD

**Issue by VidyaNallathimmayyagari** [Azure/azure-iot-pcs-remote-monitoring-dotnet#135]
# Type of issue 
- [x ] Bug
- [ ] New feature
- [ ] Improvement

While trying to deploy via CLI and using West US 2, it fails with the following error -

Deployment validation failed:
{
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: 'The provided value 'eastus 2' for the template parameter 'tsiLocation' at line '1' and column '15372' is not valid. The parameter value is not part of the allowed value(s): 'eastus,eastus2,westus,westus2,westcentralus,northeurope,westeurope'.'."
}

**Comment by asdonald** [comment]
@VidyaNallathimmayyagari This issue has been fixed.
