### ISSUE TITLE
ASA Stream Analytics JOB

### ISSUE THREAD

**Issue by tudorian** [Azure/azure-iot-pcs-remote-monitoring-dotnet#136]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description 
How do you configure the Stream Analytics JOB for the ASA Manager. I cannot find any reference in the manual deployment procedure ?

**Comment by asdonald** [comment]
@tudorian Can you please elaborate on what you mean by "configure"?

**Comment by asdonald** [comment]
@tudorian Closing due to no response. Please re-open if you still have any questions / issues.
