### ISSUE TITLE
Devices page has stopped showing Firmware values

### ISSUE THREAD

**Issue by aditidugar** [Azure/azure-iot-pcs-remote-monitoring-dotnet#139]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Deployed a solution through solutions.com on 10/4/2018. At that time everything was showing correctly. Opened same solution on 10/24 and cannot see the Firmware version on the Devices page for any of the simulated devices.

# Screenshot 
![image](https://user-images.githubusercontent.com/29984175/47463169-5113fd00-d79a-11e8-95d2-485f0f894d57.png)

# Steps to reproduce 
Unsure how to reproduce, but can provide link to solution.

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by sushilraje** [comment]
Resolved in ADM
