### ISSUE TITLE
ETIMEDOUT error when provisioning Azure resources for local dev environment

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-iot-pcs-remote-monitoring-dotnet#144]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I am trying to setup the Azure resources to setup a local development environment.
When executing the file `start.cmd` on folder `services\scripts\local\launch`, the script starts to deploy services, but it eventually fails with the following error:
`- Deploying...Error: Long running operation failed with error: "connect ETIMEDOUT 51.144.236.151:443"`

The Azure resources are indeed provisioned, but some of their configurations are missing (for instance, cosmos collections) and the environment variables are never added to the local system.

Exact log:
```
Creating Azure resources ... This operation might fail if you are not logged in. Please login and try again.
? Enter a solution name: luisdel-dev-rm-pcs
? Select a subscription: Visual Studio Ultimate with MSDN
? Select a location: West Europe
✓ Application registered: https://portal.azure.com/xxx.onmicrosoft.com#blade/Microsoft_AAD_IAM/ApplicationBlade/objectId/ca9445d7-fcfb-4801-xxx-6b725cdd9d51/appId/xxx-0168-4f03-95e0-79a2dcc3d59f
✓ Created resource group: https://portal.azure.com/xxx.onmicrosoft.com#resource/subscriptions/xxx-cad6-4230-9b9e-ae4837ed65ba/resourceGroups/xxx-dev-rm-pcs
- Deploying...Error: Long running operation failed with error: "connect ETIMEDOUT 51.144.236.151:443".
✕ Error: Long running operation failed with error: "connect ETIMEDOUT 51.144.236.151:443".
```

# Screenshot 

# Steps to reproduce 
Run `start.cmd` to setup Azure resources for local development environment.

# Expected behavior 
Azure resources are properly provisioned and configured.

# Current behavior 

# Known workarounds 

# Possible solution 

# Context and Environment
* Operating System:  Win10
* GitHub branch: master
* .NET Runtime: Core 2.1

**Comment by elvinm** [comment]
This may have been an intermittent issue at the time where some resources were not available. I was able to deploy multiple instances in different regions including West Europe as shown. Please reopen if you are still seeing issues.

**Comment by kalyanb9119** [comment]
I am getting same issue continuously 

`2019-07-11T09:10:23.815 INFO d:\a\1\s\publish\deployui.js:40 Running ARM template validation before deploying resources
2019-07-11T09:10:31.061 INFO d:\a\1\s\publish\deployui.js:98 ✓ ARM template Deployment validation succeeded.

2019-07-11T09:10:31.061 INFO d:\a\1\s\publish\deployui.js:40 
2019-07-11T09:17:15.477 ERROR d:\a\1\s\publish\datahubdeployment.js:234 { Error: Long running operation failed with error: "connect ETIMEDOUT 52.183.69.76:443".
    at PollingState.getCloudError (d:\a\1\s\node_modules\ms-rest-azure\lib\pollingState.js:127:17)
    at d:\a\1\s\node_modules\ms-rest-azure\lib\azureServiceClient.js:156:38
    at d:\a\1\s\node_modules\ms-rest-azure\node_modules\async\dist\async.js:958:16
    at next (d:\a\1\s\node_modules\ms-rest-azure\node_modules\async\dist\async.js:5208:25)
    at d:\a\1\s\node_modules\ms-rest-azure\lib\azureServiceClient.js:129:20
    at _getStatus (d:\a\1\s\node_modules\ms-rest-azure\lib\azureServiceClient.js:169:21)
    at d:\a\1\s\node_modules\ms-rest-azure\lib\azureServiceClient.js:284:14
    at retryCallback (d:\a\1\s\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyFilter.js:89:9)
    at retryCallback (d:\a\1\s\node_modules\ms-rest\lib\filters\exponentialRetryPolicyFilter.js:140:9)
    at d:\a\1\s\node_modules\ms-rest\lib\filters\rpRegistrationFilter.js:33:16
  request:
   { rawResponse: false,
     queryString: {},
     url:
      'https://management.azure.com/subscriptions/da9091ec-d18f-456c-9c21-5783ee7f4645/resourcegroups/farmbeats-installer/providers/Microsoft.Resources/deployments/deployment-farmbeats-installer-datahub/operationStatuses/08586387706523239264?api-version=2017-05-10',
     method: 'GET',
     headers:
      { 'user-agent':
         'Node/v10.16.0 (x64-Windows_NT-10.0.17763) ms-rest/2.5.0 ms-rest-azure/2.6.0 azure-arm-resource/3.0.0-preview Azure-SDK-For-Node' },
     body: null },
  response:
   { body: '{"status":"Running"}',
     headers:
      { 'cache-control': 'no-cache',
        pragma: 'no-cache',
        'content-type': 'application/json; charset=utf-8',
        expires: '-1',
        'x-ms-ratelimit-remaining-subscription-reads': '11984',
        'x-ms-request-id': '6d23948c-346a-45c2-9e0c-870d88a79657',
        'x-ms-correlation-request-id': '6d23948c-346a-45c2-9e0c-870d88a79657',
        'x-ms-routing-request-id':
         'WESTUS2:20190711T091342Z:6d23948c-346a-45c2-9e0c-870d88a79657',
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        'x-content-type-options': 'nosniff',
        date: 'Thu, 11 Jul 2019 09:13:42 GMT',
        connection: 'close',
        'content-length': '20' },
     statusCode: 200 },
  message:
   'Long running operation failed with error: "connect ETIMEDOUT 52.183.69.76:443".',
  body: { status: 'Running' } }`
