### ISSUE TITLE
Unable to run device simulation service

### ISSUE THREAD

**Issue by ckmani** [Azure/azure-iot-pcs-remote-monitoring-dotnet#153]
# Type of issue 
- [ X] Bug
- [ ] New feature
- [ ] Improvement

# dotnet: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: file too short 
.

# Steps to reproduce 
1. while initiating \services\device-simulation\scripts\docker\run.cmd it throws the error and i have followed all the mentioned steps from (https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) and moreover i have tried with the latest testing image also(DS-2.0.2-testing) still am facing the same issue.

# Operating System
Windows 10

**Comment by sushilraje** [comment]
@ckmani This looks like an error log from the container while device-simulation is booting up. 
1. Did you build device simulation locally? 
2. Can you try removing the device simulation container and image and retry the command? 
3. Also, have you switched to Linux containers on docker for Windows

**Comment by ckmani** [comment]
@sushilraje  its working now i have removed the container and added it again.But am unable to load the map component in the UI its throwing error.Is the following JS decommissioned ? https://atlas.microsoft.com/sdk/js/atlas.min.js?api-version=2.0
![map](https://user-images.githubusercontent.com/5591808/53937778-26389e80-40d4-11e9-95cb-c296cbb38332.png)

**Comment by ckmani** [comment]
@sushilraje  any updates on the above
