### ISSUE TITLE
Any api documents like swagger?

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/azure-iot-pcs-remote-monitoring-dotnet#157]
If we want to build our own web ui solutions based on Angular or get the device telemetry data in a Unity 3D ui. Where can I find the api reference documents ?

**Comment by ppathan** [comment]
https://github.com/Azure/remote-monitoring-services-dotnet/wiki for dotnet
https://github.com/Azure/remote-monitoring-services-java/wiki for java
