### ISSUE TITLE
Device Sim won't start correctly

### ISSUE THREAD

**Issue by Rob-amrc** [Azure/azure-iot-pcs-remote-monitoring-dotnet#159]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I've been trying to deploy locally for a few days now following this [guide](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) but have had very little luck, whilst the services start in visual studio fine I have the following errors on the webservices:
```
DeviceTelemtry: Diagnostics
IsHealthy false
Message "Status code: 0; Response: An error occurred while sending the request. - A connection with the server could not be established"

ASAManager:Config
IsHealthy false
Message "DeviceSimulation check failed"

Config:
DeviceSimulation
IsHealthy false
Message "ERROR:Unable to use Storage"
```

The Device sim also appears to be ignoring the env-vars set in both device and docker-compose.yml and had a few errors that I'd managed to rectify by setting a few additional env-vars but is still reporting the following:

`devicesimulation_1 | [ERROR][2019-04-10 14:14:36.151][WebService.8955e47b-82f3-4f18-8085-a1c323102c29][AuthMiddleware:InitializeTokenValidationAsync] Failed to setup OpenId Connect, {"e":{"ExceptionFullName":"System.InvalidOperationException","ExceptionMessage":"IDX10803: Unable to obtain configuration from: '.well-known/openid-configuration'.","StackTrace":" at Microsoft.IdentityModel.Protocols.ConfigurationManager1.&lt;GetConfigurationAsync&gt;d__24.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at Microsoft.Azure.IoTSolutions.DeviceSimulation.WebService.Auth.AuthMiddleware.&lt;InitializeTokenValidationAsync&gt;d__15.MoveNext() in /home/azureiotpcs/vsts-agent/_work/46/s/WebService/Auth/AuthMiddleware.cs:line 204","Source":"Microsoft.IdentityModel.Protocols","Data":{},"InnerException":{"ExceptionFullName":"System.ArgumentException","ExceptionMessage":"IDX10108: The address specified is not valid as per HTTPS scheme. Please specify an https address for security reasons. If you want to test with http address, set the RequireHttps property on IDocumentRetriever to false.\nParameter name: .well-known/openid-configuration","StackTrace":" at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.&lt;GetDocumentAsync&gt;d__8.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()\n at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()\n at Microsoft.IdentityModel.Protocols.ConfigurationManager1.<GetConfigurationAsync>d__24.MoveNext()","Source":"Microsoft.IdentityModel.Protocols","Data":{},"InnerException":null}},`

# Screenshot 
![image](https://user-images.githubusercontent.com/19547513/55949756-3e5b8a80-5c4b-11e9-8d38-f9205053a572.png)

# Steps to reproduce 
1. Follow the deploy locally [guide](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) 

# Expected behavior 
Local deployment including device simulator starts and runs correctly

# Current behavior 
Device Simulator doesnt appear to be starting correctly and isn't linking up with the other microservices correctly during local deployment

# Known workarounds 
...

# Possible solution 
Possible missing information on the deploy locally guide or missing environment variables

# Context and Environment
* Operating System: Windows 10
* GitHub branch: default
* .NET Runtime: ...

**Comment by ppathan** [comment]
@sushilraje Can you please take a look?

**Comment by sushilraje** [comment]
This is an error if auth is not enabled. It is perfectly ok.
