### ISSUE TITLE
Remote Monitoring local deployment not working - Device Simulation service

### ISSUE THREAD

**Issue by VJReDdy** [Azure/azure-iot-pcs-remote-monitoring-dotnet#162]
# Type of issue 
- [ ] Bug
Device simulation service (running in docker for Windows) throws an exception that... not able to reach Storage Service.
- [ ] New feature
- [ ] Improvement

# Description 
Trying to setup local instance of Remote Monitoring application.
Followed the steps mentioned in...
All the services (except Device Simulation) are started in debug mode in Visual Studio 2017.
Device simulation (docker) throws an error saying not able to reach storage service which is running on host (http://localhost:9022/v1).
[Stated docker image without "--detach" in run.cmd to see logs]

My observation:
I see Device Simulation service is trying to reach Storage service using "http://localhost:9022/v1/" though the run.cmd has an environment variable for storage service with value "http://host.docker.internal:9022/v1".

# Screenshot 

# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by VJReDdy** [comment]
Followed steps mentioned in...
https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local

**Comment by VJReDdy** [comment]
Any update on this defect? please update. Thanks.

**Comment by akashlomas** [comment]
I am facing the same issue, I would appreciate help on the possible solution to this issue.

**Comment by ChristineChetty11** [comment]
Same issue here

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
