### ISSUE TITLE
What's the value of REACT_APP_BASE_SERVICE_URL to deploy locally?

### ISSUE THREAD

**Issue by Trinakriae** [Azure/azure-iot-pcs-remote-monitoring-dotnet#163]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
In order to deploy the solution locally, it is not specified in the [documentation](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local) what's the value of the environment variable REACT_APP_BASE_SERVICE_URL in the WebUI. I tried to put http://localhost:9000 since I was expecting nginx acting as an API Gateway/Reverse Proxy but I always get 503 - Service Unavailable. May you please help?

# Context and Environment
* Operating System: Windows 10
* GitHub branch: https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

**Comment by Alberto-Vega-MSFT** [comment]
@Trinakriae Have you tried the steps listed here: https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-customize#prepare-a-local-development-environment-for-the-ui

**Comment by Alberto-Vega-MSFT** [comment]
Can you confirm that you followed this step? https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local#configure-and-run-nginx

**Comment by Alberto-Vega-MSFT** [comment]
@Trinakriae do you have an update?

**Comment by Trinakriae** [comment]
Yes I’ve followed the steps listed in that article and the mentioned environment variable does not get set

**Comment by Alberto-Vega-MSFT** [comment]
@Trinakriae please reach out so we can get you help from a support engineer. If you don't have access to a support plan follow the instructions on my previous comment and we can help get a one time free support ticket.

**Comment by NoirRyu** [comment]
Any update on this? I have also same problem, whenever deploy on my Windows 10 local machine, the webui doesn't seem to properly communicate with other services. I also thought I need to set REACT_APP_BASE_SERVICE_URL variable to enable webui to communicate with other services.

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
