### ISSUE TITLE
Fork or Contribute?

### ISSUE THREAD

**Issue by andrewschmidt-a** [Azure/azure-iot-pcs-remote-monitoring-dotnet#164]
# Type of issue 
- [ ] Bug
- [x] New feature
- [x] Improvement

# Description 
...
I work at 3M company and we are building out IoT Solutions.
We wanted to build a version of this project that would be multi-tenanted.(with true isolation) This is such a big change and would result in a massive PR. 
Is this something we ought to just Fork and diverge? Or is it something that this project may be interested in taking in?

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
