### ISSUE TITLE
Missing icon fonts!

### ISSUE THREAD

**Issue by ByteCode2408** [Azure/azure-iot-pcs-remote-monitoring-dotnet#165]
# Type of issue 
- [X ] Bug
- [ ] New feature
- [ ] Improvement

# Description 
https://static.azureiotcentral.com/ux/static/media/segmdl2.1.61.38af5f02.woff and
https://static.azureiotcentral.com/ux/static/media/segmdl2.1.61.35c95dc2.ttf required in Web UI are missing since few days!

**Comment by BeigeBadger** [comment]
I am also encountering this issue. The error I get is:

```
Access to font at 'https://static.azureiotcentral.com/ux/static/media/segmdl2.1.61.38af5f02.woff' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

and

```
Access to font at 'https://static.azureiotcentral.com/ux/static/media/segmdl2.1.61.35c95dc2.ttf' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Trying to browse to https://static.azureiotcentral.com/ux/static/media/segmdl2.1.61.38af5f02.woff directly asks me to authenticate with my MS account details, then returns a 404 error.

The above error about not being able to access the fonts occurs on my local machine, and in a hosted environment (Azure App Service).

Let me know if you need any further details.

**Comment by BeigeBadger** [comment]
So I managed to fix this by downloading the font from the link provided on [this page](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font#how-do-i-get-this-font). 

This only gets you the `.tff` file for the segmdl2 font though so I used [this site](https://convertio.co/ttf-woff/) to convert the `.tff` to a `.woff`.

I then added these files into the src\assets\fonts and updated the `@font-face` declaration in my `index.scss` file to:

```
@font-face {
  font-family: $icon-font-family;
  src: url("assets/fonts/segmdl2.woff") format('woff'),
      url("assets/fonts/segmdl2.ttf") format('truetype');
}
```

I hope this helps.

**Comment by andrewschmidt-a** [comment]
I had the same issue. Looks like iotcentral changed fonts

**Comment by ByteCode2408** [comment]
Yes, I did the same by downloading and using the font locally. Thanks!

**Comment by akingscote** [comment]
surely this shouldnt be closed until its fixed in the code

**Comment by andrewschmidt-a** [comment]
Agreed. Isnt this project in maintenance mode?

Le ven. 6 déc. 2019, à 05 h 20, akingscote <notifications@github.com> a
écrit :

**Comment by akingscote** [comment]
Oh right I didn't realize. Where did you see that? I've submitted a pull request regardless.

Sent from Workspace ONE Boxer

On 6 Dec 2019 16:27, Andrew Schmidt <notifications@github.com> wrote:
Agreed. Isnt this project in maintenance mode?

Le ven. 6 déc. 2019, à 05 h 20, akingscote <notifications@github.com> a
écrit :
