### ISSUE TITLE
Simulation No Started.   Error "Failed to seed default simulations "

### ISSUE THREAD

**Issue by coder-encoder** [Azure/azure-iot-pcs-remote-monitoring-dotnet#166]
Greetings, I have deployed the solution locally via documentation https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local-vscode

Ones I run All microservices in vs code i counter this issue.

[DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"GET"},"Uri":"http://localhost:9003/v1/simulations/1","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}
[ERROR][HttpClientWrapper:GetAsync] Request failed, {"uri":"http://localhost:9003/v1/simulations/1","StatusCode":500,"Content":""}     
[ERROR][Seed:SeedSimulationAsync] Failed to seed default simulations, {"Message":"Unable to load Simulation 1"}
[DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"PUT"},"Uri":"http://localhost:9022/v1/collections/solution-settings/values/seedMutex","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}
[WARN][RecurringTasks:SetupSeedData] Seed data setup failed, will retry in few seconds, {"pauseSecs":8,"e":{"ExceptionFullName":"System.AggregateException","ExceptionMessage":"One or more errors occurred. (Unable to load Simulation 1)","StackTrace":"   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.IoTSolutions.UIConfig.WebService.RecurringTasks.SetupSeedData(Object context) in C:\\azure-iot-pcs-remote-monitoring-dotnet\\services\\config\\WebService\\RecurringTasks.cs:line 51","Source":"System.Private.CoreLib","Data":{},"InnerExceptions":[{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.UIConfig.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load Simulation 1","StackTrace":"   at Microsoft.Azure.IoTSolutions.UIConfig.Services.Helpers.HttpClientWrapper.GetAsync[T](String uri, String description, Boolean acceptNotFound) in C:\\azure-iot-pcs-remote-monitoring-dotnet\\services\\config\\Services\\Helpers\\HttpClientWrapper.cs:line 65\r\n   at Microsoft.Azure.IoTSolutions.UIConfig.Services.External.DeviceSimulationClient.GetDefaultSimulationAsync() in C:\\azure-iot-pcs-remote-monitoring-dotnet\\services\\config\\Services\\External\\DeviceSimulationClient.cs:line 31\r\n   at Microsoft.Azure.IoTSolutions.UIConfig.Services.Seed.SeedSimulationAsync() in C:\\azure-iot-pcs-remote-monitoring-dotnet\\services\\config\\Services\\Seed.cs:line 176\r\n   at 

Thanks for any Support

**Comment by anujsharrma** [comment]
> Greetings, I have deployed the solution locally via documentation https://docs.microsoft.com/en-gb/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local-vscode
> 
> Ones I run All microservices in vs code i counter this issue.
> 
> [DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"GET"},"Uri":"[http://localhost:9003/v1/simulations/1","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}](http://localhost:9003/v1/simulations/1%22,%22Options%22:%7B%22EnsureSuccess%22:false,%22AllowInsecureSSLServer%22:false,%22Timeout%22:30000%7D%7D)
> [ERROR][HttpClientWrapper:GetAsync] Request failed, {"uri":"[http://localhost:9003/v1/simulations/1","StatusCode":500,"Content":""}](http://localhost:9003/v1/simulations/1%22,%22StatusCode%22:500,%22Content%22:%22%22%7D)
> [ERROR][Seed:SeedSimulationAsync] Failed to seed default simulations, {"Message":"Unable to load Simulation 1"}
> [DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"PUT"},"Uri":"[http://localhost:9022/v1/collections/solution-settings/values/seedMutex","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}](http://localhost:9022/v1/collections/solution-settings/values/seedMutex%22,%22Options%22:%7B%22EnsureSuccess%22:false,%22AllowInsecureSSLServer%22:false,%22Timeout%22:30000%7D%7D)
> [WARN][RecurringTasks:SetupSeedData] Seed data setup failed, will retry in few seconds, {"pauseSecs":8,"e":{"ExceptionFullName":"System.AggregateException","ExceptionMessage":"One or more errors occurred. (Unable to load Simulation 1)","StackTrace":" at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\r\n at Microsoft.Azure.IoTSolutions.UIConfig.WebService.RecurringTasks.SetupSeedData(Object context) in C:\azure-iot-pcs-remote-monitoring-dotnet\services\config\WebService\RecurringTasks.cs:line 51","Source":"System.Private.CoreLib","Data":{},"InnerExceptions":[{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.UIConfig.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load Simulation 1","StackTrace":" at Microsoft.Azure.IoTSolutions.UIConfig.Services.Helpers.HttpClientWrapper.GetAsync[T](String uri, String description, Boolean acceptNotFound) in C:\azure-iot-pcs-remote-monitoring-dotnet\services\config\Services\Helpers\HttpClientWrapper.cs:line 65\r\n at Microsoft.Azure.IoTSolutions.UIConfig.Services.External.DeviceSimulationClient.GetDefaultSimulationAsync() in C:\azure-iot-pcs-remote-monitoring-dotnet\services\config\Services\External\DeviceSimulationClient.cs:line 31\r\n at Microsoft.Azure.IoTSolutions.UIConfig.Services.Seed.SeedSimulationAsync() in C:\azure-iot-pcs-remote-monitoring-dotnet\services\config\Services\Seed.cs:line 176\r\n at
> 
> Thanks for any Support

I am also facing the same issue, any one have any resolution for this???????

**Comment by alan0428a** [comment]
I am having the issue as well, any solution for this?
Thanks.

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
