### ISSUE TITLE
Error starting telemetry and storage adapter services

### ISSUE THREAD

**Issue by pauldj54** [Azure/azure-iot-pcs-remote-monitoring-dotnet#168]
# Type of issue 
- [x ] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I cloned the latest version of the solution. Provision the resources on azure as described here [Deploy the Remote Monitoring solution accelerator locally - Docker](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local-docker).
I put the environment variables values in the .env file of the docker-compose.yml file (zure-iot-pcs-remote-monitoring-dotnet/services/scripts/local). 
After that I was getting several errors starting the containers, basically missing env variables. I got the feeling .env file was somehow not recognized so I put the missing values in the docker-compose.yml file and that solved almost all of the problems (almost all containers are now running).
I still get errors with the telemetry and storage adapter service as it can be seen in the screen shots below.
Telemetry error:
`2019-11-10T11:07:30.294767685Z [WebService.5126e04e-99c4-4e0b-abfc-1cdbafdfae26][2019-11-10 11:07:30Z][WARN][ConfigData:GetSecrets] Value for secret TelemetryService:Messages:telemetryStorageType not found in local env.  Trying to get the secret from KeyVault.
2019-11-10T11:07:30.345568970Z [WebService.5126e04e-99c4-4e0b-abfc-1cdbafdfae26][2019-11-10 11:07:30Z][ERROR][KeyVault:GetSecret] Secret telemetryStorageType not found in Key Vault.
`
Storage adapter error:
`2019-11-10T11:07:24.451155417Z [WebService.9269564a-5d05-4769-9ac3-cae46b7b9103][2019-11-10 11:07:24Z][WARN][ConfigData:GetSecrets] Value for secret StorageAdapter:documentDBConnectionString not found in local env.  Trying to get the secret from KeyVault.
2019-11-10T11:07:24.497866710Z [WebService.9269564a-5d05-4769-9ac3-cae46b7b9103][2019-11-10 11:07:24Z][ERROR][KeyVault:GetSecret] Secret documentDBConnectionString not found in Key Vault.`

# Screenshot 
1. Docker ps -a
![image](https://user-images.githubusercontent.com/706754/68543252-fa815d00-03b4-11ea-81c2-6de41d9a5d43.png)

2. Docker logs telemetry:
![image](https://user-images.githubusercontent.com/706754/68543268-27357480-03b5-11ea-9f0a-726c595c8f0c.png)

3. Docker logs storage adapter
![image](https://user-images.githubusercontent.com/706754/68543276-492ef700-03b5-11ea-829a-961874e017b5.png)

4. Docker inspect - Here I was able to find all env variables in both containers (side note: I have not killed the screenshot )
![image](https://user-images.githubusercontent.com/706754/68543960-34a32c80-03be-11ea-99fb-ddaf9cc45b64.png)

# Steps to reproduce 
1. Clone solution
2. Populate .env and docker-compose.yml file
3. Run containers with docker-compose up 

# Expected behavior 
All containers are running

# Current behavior 
Telemetry and storage adapter services exited with errors. 

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Open SUSE Leap 15.1 VM running on oracle VBox on Windows 10 Pro.
* GitHub branch: Master
* .NET Runtime: Dotnet Core SDK 2.1.802

**Comment by anujsharrma** [comment]
Any updates on this i am also getting the same error.

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
