### ISSUE TITLE
Run start.sh in linux machine 

### ISSUE THREAD

**Issue by navidarry** [Azure/azure-iot-pcs-remote-monitoring-dotnet#171]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
In Linux for development locally, I ran `bash start.sh` in command line, below error occured:
`./start.sh: line 14: /home/navid/Projects/azure-iot-pcs-remote-monitoring-dotnet/services/scripts/local/launch/helpers/create-azure-resources.sh: Permission denied`

# Possible solution 
in line 14, replace line with this:
`. $APP_HOME/scripts/local/launch/helpers/create-azure-resources.sh;`

# Context and Environment
* Operating System: openSUSE Leap kernel 15.1 4.12.14-lp151.28.48-default x86_64 GNU/Linux

**Comment by magixus** [comment]
Hello,

I had the same issue and managed to fix it by simply run this command :
>  ```cd /home/navid/Projects/azure-iot-pcs-remote-monitoring-dotnet/services/scripts/local/launch && pcs```

It would then prompt you to fill in project information.

![image](https://user-images.githubusercontent.com/7642058/89351796-a472e900-d6aa-11ea-861b-43106c789632.png)

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
