### ISSUE TITLE
Linux machine ./start.sh does not recongnize node version

### ISSUE THREAD

**Issue by navidarry** [Azure/azure-iot-pcs-remote-monitoring-dotnet#172]
# Type of issue
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
for development locally for testing, i ran `bash ./start.sh` but node version error occured whereas node v8.17.3 installed

# Context and Environment
*  Operating System: openSUSE Leap kernel 15.1 4.12.14-lp151.28.48-default x86_64 GNU/Linux

**Comment by magixus** [comment]
Hi, 

I solved this by install `dos2unix` command line and convert `pcs` [node package files to unix files.](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo)
* I've installed `pcs` using ```yarn global add iot-solutions```
* So `pcs` node package (on my case) was installed on `$HOME/.config/yarn/global/node_modules/iot-solutions/`
   ![image](https://user-images.githubusercontent.com/7642058/89351111-3a0d7900-d6a9-11ea-8d20-b6bc4e32512a.png)
 * Then I (bulk) converted all those file with dos2unix with :
     ```cd $HOME/.config/yarn/global/node_modules/iot-solutions/ && find . -type f -print0 | xargs -0 dos2unix```
* Finally a `pcs login` would successfully log me in my azure subscription

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
