### ISSUE TITLE
Error: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details

### ISSUE THREAD

**Issue by magixus** [Azure/azure-iot-pcs-remote-monitoring-dotnet#173]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I'm running ubuntu 20.04 LTS and tried to install remote monitoring locally with docker.
When I try to create `Azure resources` with `pcs` i get this error (twice till now)
...
✓ Provisioning State: Succeeded Resource Type: Microsoft.Devices/Iothubs/Iothubkeys
✕ Error: Long running operation failed with error: "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.".

# Screenshot 

![terminal error](https://user-images.githubusercontent.com/7642058/89352869-0df3f700-d6ad-11ea-8344-8afc9259fbbb.png)

![error on portal](https://user-images.githubusercontent.com/7642058/89353215-e0f41400-d6ad-11ea-8c75-f37af2b7a292.png)

![error details](https://user-images.githubusercontent.com/7642058/89353263-f701d480-d6ad-11ea-868f-6bdb4ac17b3b.png)

# Steps to reproduce 

* I've installed `pcs` with `yarn global add iot-solutions`
* I've converted iot-solutions node packages DOS files format to unix with :
  * ```find $HOME/.config/yarn/global/node_modules/iot-solutions/ -type f -print0 | xargs -0 dos2unix```
* Download this repo:
  * `git clone <this repo>`
* `cd to azure-iot-pcs-remote-monitoring-dotnet/services/scripts/local/launch`
> After runnning into two issues #171  #172 i've managed to create resources with only executing :
  * pcs login
  * pcs
> that prompt me to fill in my project information and start creating resources.

# Expected behavior 
Create all azure iot resources.

# Current behavior 
Failed to create azure resources.

# Known workarounds 
...

# Possible solution 
fix this error: 
```
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'scriptextensions'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=1\\n[stdout]\\nExit code: 1\\nSetup failed, please see log file '/app/setup.log' for more information\\n\\n[stderr]\\n\\\"\\r\\n\\r\\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot \"\r\n }\r\n ]\r\n }\r\n}"}]}
```

# Context and Environment
* Operating System: Ubuntu 20.04 LTS
* GitHub branch: master
* .NET Runtime: 3.1.302
* Nodejs : 12.18.3

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
