### ISSUE TITLE
Fail to deploy the remote monitoring solution accelerator locally with Docker 

### ISSUE THREAD

**Issue by alan0428a** [Azure/azure-iot-pcs-remote-monitoring-dotnet#174]
# Type of issue 
- [x] Bug
- [ ] Improvement
- [ ] New feature

# Description 
I am following the instructions on[ IoT solutions accelerators documentation ](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local-docker). I've created Azure services through "start.cmd". But after I run "docker-compose up", some of the services run in my local docker log error messages. And the webUI on port 8080 didn't show correct content as well.

The following are the log messages. Please let me know if you need further information. 

`devicesimulation_1  | [ERROR][2020-10-18 13:16:56.778][WebService.bfa12f98-f2e7-4915-b5dd-01673aaea0e7][HttpClient:SendAsync] Request failed, {"timeSpentMsecs":2,"Method":"GET","Uri":"http://localhost:9022/v1/collections/simulations/values","errorMessage":"An error occurred while sending the request. - Couldn't connect to server","e":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"An error occurred while sending the request.","StackTrace":"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Http.HttpClient.<SendAsync>d__9.MoveNext() in C:\\builds\\device-simulation-dotnet\\Services\\Http\\HttpClient.cs:line 92","Source":"System.Private.CoreLib","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.CurlException","ExceptionMessage":"Couldn't connect to server","StackTrace":"   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)\n   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)","Source":"System.Net.Http","Data":{},"InnerException":null}}}
devicesimulation_1  | [ERROR][2020-10-18 13:16:56.779][WebService.bfa12f98-f2e7-4915-b5dd-01673aaea0e7][Agent:RunAsync] Failure reading and starting simulation from storage., {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"An unexpected error happened while using an external dependency.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.ThrowIfError(IHttpResponse response, String collectionId, String key) in C:\\builds\\device-simulation-dotnet\\Services\\StorageAdapter\\StorageAdapterClient.cs:line 172\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.StorageAdapter.StorageAdapterClient.<GetAllAsync>d__7.MoveNext() in C:\\builds\\device-simulation-dotnet\\Services\\StorageAdapter\\StorageAdapterClient.cs:line 84\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Simulations.<GetListAsync>d__9.MoveNext() in C:\\builds\\device-simulation-dotnet\\Services\\Simulations.cs:line 85\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.Agent.<RunAsync>d__7.MoveNext() in C:\\builds\\device-simulation-dotnet\\SimulationAgent\\Agent.cs:line 51","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"Storage request error: status code 0","StackTrace":null,"Source":null,"Data":{},"InnerException":null}}}`

`iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][INFO][Agent:BuildDevicePropertiesCache] Creating DeviceProperties cache...
iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"GET"},"Uri":"http://localhost:9022/v1/collections/device-twin-properties/values/cache","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}
iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][ERROR][HttpClient:SendAsync] Request failed, {"ExceptionMessage":"An error occurred while sending the request.","InnerExceptionType":"System.Net.Http.CurlException","InnerExceptionMessage":"Couldn't connect to server","errorMessage":"An error occurred while sending the request. - Couldn't connect to server"}
iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][INFO][StorageAdapterClient:CheckStatusCode] StorageAdapter returns 0 for request http://localhost:9022/v1/collections/device-twin-properties/values/cache, {"Uri":"http://localhost:9022/v1/collections/device-twin-properties/values/cache","StatusCode":0,"Content":"An error occurred while sending the request. - Couldn't connect to server"}
iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][DEBUG][Agent:BuildDevicePropertiesCache] DeviceProperties Cache creation failed, will retry in few seconds, {"CACHE_INIT_RETRY_SECS":10}
iothubmanager_1     | [WebService.88bdc421-aff3-4447-8a25-2035130e4fca][2020-10-18 13:16:52Z][WARN][Agent:BuildDevicePropertiesCache] Pausing thread before retrying DeviceProperties cache creation, {"CACHE_INIT_RETRY_SECS":10}`

`config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][INFO][RecurringTasks:SetupSeedData] Creating seed data...
config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][DEBUG][HttpClient:SendAsync] Sending request, {"httpMethod":{"Method":"GET"},"Uri":"http://localhost:9022/v1/collections/solution-settings/values/seedMutex","Options":{"EnsureSuccess":false,"AllowInsecureSSLServer":false,"Timeout":30000}}
config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][ERROR][HttpClient:SendAsync] Request failed, {"ExceptionMessage":"An error occurred while sending the request.","InnerExceptionType":"System.Net.Http.CurlException","InnerExceptionMessage":"Couldn't connect to server","errorMessage":"An error occurred while sending the request. - Couldn't connect to server"}
config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][INFO][StorageAdapterClient:CheckStatusCode] StorageAdapter returns 0 for request http://localhost:9022/v1/collections/solution-settings/values/seedMutex, {"Uri":"http://localhost:9022/v1/collections/solution-settings/values/seedMutex","StatusCode":0,"Content":"An error occurred while sending the request. - Couldn't connect to server"}
config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][WARN][RecurringTasks:SetupSeedData] Seed data setup failed, will retry in few seconds, {"pauseSecs":8,"e":{"ExceptionFullName":"System.AggregateException","ExceptionMessage":"One or more errors occurred. (Http request failed, status code = 0, content = An error occurred while sending the request. - Couldn't connect to server, request URL = http://localhost:9022/v1/collections/solution-settings/values/seedMutex)","StackTrace":"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n   at Microsoft.Azure.IoTSolutions.UIConfig.WebService.RecurringTasks.SetupSeedData(Object context) in /home/azureiotpcs/vsts-agent/_work/20/s/config/WebService/RecurringTasks.cs:line 51","Source":"System.Private.CoreLib","Data":{},"InnerExceptions":[{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"Http request failed, status code = 0, content = An error occurred while sending the request. - Couldn't connect to server, request URL = http://localhost:9022/v1/collections/solution-settings/values/seedMutex","StackTrace":"   at Microsoft.Azure.IoTSolutions.UIConfig.Services.External.StorageAdapterClient.CheckStatusCode(IHttpResponse response, IHttpRequest request) in /home/azureiotpcs/vsts-agent/_work/20/s/config/Services/External/StorageAdapterClient.cs:line 118\n   at Microsoft.Azure.IoTSolutions.UIConfig.Services.External.StorageAdapterClient.<GetAsync>d__4.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/config/Services/External/StorageAdapterClient.cs:line 34\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.UIConfig.Services.Helpers.StorageMutex.<EnterAsync>d__4.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/config/Services/Helpers/StorageMutex.cs:line 39\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.UIConfig.Services.Seed.<TrySeedAsync>d__12.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/config/Services/Seed.cs:line 64","Source":"Microsoft.Azure.IoTSolutions.UIConfig.Services","Data":{},"InnerException":null}]}}
config_1            | [WebService.3c2b26be-ae12-4734-94c4-746b3bdc1738][2020-10-18 13:16:46Z][WARN][RecurringTasks:SetupSeedData] Pausing thread before retrying seed data, {"pauseSecs":8}`

`asamanager_1        | [ERROR][2020-10-18 13:16:35.185][WebService.11e88f80-08c4-4c50-874a-a1c95c4958a2][HttpClient:SendAsync] Request failed, {"timeSpent":3,"Method":"GET","Uri":"http://localhost:9005/v1/devicegroups/","errorMessage":"An error occurred while sending the request. - Couldn't connect to server","e":{"ExceptionFullName":"System.Net.Http.HttpRequestException","ExceptionMessage":"An error occurred while sending the request.","StackTrace":"   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\n   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Http.HttpClient.<SendAsync>d__10.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/Services/Http/HttpClient.cs:line 142","Source":"System.Private.CoreLib","Data":{},"InnerException":{"ExceptionFullName":"System.Net.Http.CurlException","ExceptionMessage":"Couldn't connect to server","StackTrace":"   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)\n   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)","Source":"System.Net.Http","Data":{},"InnerException":null}}}
asamanager_1        | [ERROR][2020-10-18 13:16:35.185][WebService.11e88f80-08c4-4c50-874a-a1c95c4958a2][HttpClient:GetJsonAsync] Request failed, {"uri":"http://localhost:9005/v1/devicegroups/","StatusCode":0,"Content":"An error occurred while sending the request. - Couldn't connect to server"}
asamanager_1        | [ERROR][2020-10-18 13:16:35.186][WebService.11e88f80-08c4-4c50-874a-a1c95c4958a2][DeviceGroupsClient:GetDeviceGroupsAsync] Failed to get list of device groups, {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.AsaManager.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load get device groups","StackTrace":"   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Http.HttpClient.<GetJsonAsync>d__9`1.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/Services/Http/HttpClient.cs:line 104\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.AsaManager.DeviceGroupsAgent.DeviceGroupsClient.<GetDeviceGroupsAsync>d__8.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/DeviceGroupsAgent/DeviceGroupsClient.cs:line 78","Source":"Microsoft.Azure.IoTSolutions.AsaManager.Services","Data":{},"InnerException":null}}
asamanager_1        | [ERROR][2020-10-18 13:16:35.187][WebService.11e88f80-08c4-4c50-874a-a1c95c4958a2][Agent:RunAsync] Received error updating device to device group mapping, {"e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.AsaManager.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to get list of device groups","StackTrace":"   at Microsoft.Azure.IoTSolutions.AsaManager.DeviceGroupsAgent.DeviceGroupsClient.<GetDeviceGroupsAsync>d__8.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/DeviceGroupsAgent/DeviceGroupsClient.cs:line 83\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.AsaManager.DeviceGroupsAgent.Agent.<RunAsync>d__13.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/DeviceGroupsAgent/Agent.cs:line 85","Source":"Microsoft.Azure.IoTSolutions.AsaManager.DeviceGroupsAgent","Data":{},"InnerException":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.AsaManager.Services.Exceptions.ExternalDependencyException","ExceptionMessage":"Unable to load get device groups","StackTrace":"   at Microsoft.Azure.IoTSolutions.AsaManager.Services.Http.HttpClient.<GetJsonAsync>d__9`1.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/Services/Http/HttpClient.cs:line 104\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.IoTSolutions.AsaManager.DeviceGroupsAgent.DeviceGroupsClient.<GetDeviceGroupsAsync>d__8.MoveNext() in /home/azureiotpcs/vsts-agent/_work/20/s/asa-manager/DeviceGroupsAgent/DeviceGroupsClient.cs:line 78","Source":"Microsoft.Azure.IoTSolutions.AsaManager.Services","Data":{},"InnerException":null}}}`

# Screenshot 

![image](https://user-images.githubusercontent.com/23318971/96369298-a584c400-118b-11eb-8f76-88d86e30e927.png)
![image](https://user-images.githubusercontent.com/23318971/96369314-b46b7680-118b-11eb-94ef-ca4e97f38453.png)

# Steps to reproduce 
Following the same steps on[ IoT solutions accelerators documentation ](https://docs.microsoft.com/en-us/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local-docker)

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Windows 10 Pro
* GitHub branch: master
* .NET Runtime: 3.1.401

**Comment by miwolfms** [comment]
Note: As of December 10th 2020, Remote Monitoring solution accelerator is no longer supported. All supporting repositories have been archived.
