### ISSUE TITLE
Total occurrences number doesn't match 

### ISSUE THREAD

**Issue by hegate** [Azure/azure-iot-pcs-remote-monitoring-dotnet#22]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description
In system alarms, total nmber of occurrences always points to 1, and it should match the number of total alarms.

In this case, I haven't closed or ack any alarm, so it should say 52 open occurrences

![image](https://user-images.githubusercontent.com/12633955/30935273-fe7b1eec-a384-11e7-8d30-6c93260b6f22.png)

# Steps to reproduce

1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior

...

# Current behavior

...

# Known workarounds

...

# Possible solution

...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

# Code to reproduce the bug

```
using Xunit;

public class MyTest
{
    [Fact]
    public void TestToReproduceIssue()
    {
        // Arrange
        ...

        // Act
        ...

        // Assert
        ...
    }
}
```

**Comment by timlaverty** [comment]
dup of https://github.com/Azure/pcs-remote-monitoring-webui/issues/678
