### ISSUE TITLE
Missing values for environment variables on docker-compose.yml

### ISSUE THREAD

**Issue by franji** [Azure/azure-iot-pcs-remote-monitoring-dotnet#27]
# Type of issue

- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description
When docker-compose is launched, although some containers do start, there are multiple errors due to missing values for environment variables.
Some of them can be guessed by looking at the error messages, but not all of them. 

# Context and Environment
* Operating System: Windows 10
* GitHub branch: master
* .NET Runtime: 4.0
* Docker for Windows: Version 17.09.0-ce-win33

**Comment by dluc** [comment]
@jillcary I think we can reuse the work you've done recently to address this issue

**Comment by jillcary** [comment]
The documentation has been updated for running the solution locally [here](https://docs.microsoft.com/azure/iot-accelerators/iot-accelerators-remote-monitoring-deploy-local).

Let us know if this doesn't work for you.
