### ISSUE TITLE
"Upgrade map key to see devices on a dynamic map" Content is Empty

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-pcs-remote-monitoring-dotnet#39]
# Type of issue

- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description

The section titled "Upgrade map key to see devices on a dynamic map" on the wiki under "Developer Reference Guide" - "Customization" is empty. 

# Steps to reproduce

1. Go to wiki.
2. Select "Developer Reference Guide".
3. Under "Contents", select "Upgrade map key to see devices on a dynamic map".

# Expected behavior

This section should have content for how to add an interactive map to the solution.

# Current behavior

There is no content.

# Possible solution

There may be some documentation leftover from the previous implementation of the preconfigured solution that could be used, but I don't know where to find it.

**Comment by scout208** [comment]
Grammar

**Comment by ppathan** [comment]
Fixed.
