### ISSUE TITLE
Updating Simulated Device Firmware Doesn't Update Firmware Version

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-pcs-remote-monitoring-dotnet#41]
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description

Following the instructions on [Operate the preconfigured solution - Update device firmware](https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-remote-monitoring-explore#update-device-firmware) to update prototype device firmware doesn't update device firmware version.

# Steps to reproduce

1. Navigate to the **Devices** page. Choose the **Prototyping devices** filter in the **Filters** drop-down:

![image](https://user-images.githubusercontent.com/9426329/32388883-2178477e-c097-11e7-84ae-50024adbe5d9.png)

2. Select one of the prototyping devices:

![image](https://user-images.githubusercontent.com/9426329/32388904-2d73a96a-c097-11e7-80b5-bef5104e67d6.png)

3. Click the Schedule button and then choose Firmware update. Enter values for Job name and Firmware URI. Choose Apply to schedule the job to run now:

![image](https://user-images.githubusercontent.com/9426329/32388923-3b428c96-c097-11e7-8e32-11b18bc88c93.png)

4. Choose **Apply**:

![image](https://user-images.githubusercontent.com/9426329/32389125-c9e9db2a-c097-11e7-96a1-460d9a192c76.png)

5. Wait for the job to complete.

![image](https://user-images.githubusercontent.com/9426329/32389224-1954b914-c098-11e7-9f68-53b457e099b4.png)

6. Navigate back to the **Devices** page and check the Firmware version. 

![image](https://user-images.githubusercontent.com/9426329/32389291-4d79e048-c098-11e7-9dc0-53e81b1146b9.png)

# Expected behavior

The firmware version should change to display 2.0.0 after running the FirmwareUpdate method on the device.

# Current behavior

The firmware version remains the same after running the FirmwareUpdate method on the device.

# Known workarounds

None.

# Possible solution

This works on the stable version of the preconfigured solution, so maybe there's a hint to a solution in that?

# Context and Environment
* Operating System: Microsoft Edge
* GitHub branch: master
* .NET Runtime: ???

**Comment by timlaverty** [comment]
Related to: https://github.com/Azure/pcs-remote-monitoring-webui/issues/753, https://github.com/Azure/pcs-remote-monitoring-webui/issues/427

**Comment by ppathan** [comment]
Fixed.
