### ISSUE TITLE
Authenticate to the VM

### ISSUE THREAD

**Issue by dotnet007** [Azure/azure-iot-pcs-remote-monitoring-dotnet#45]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Please explain in the developer guide in the section of connecting to the VM that you must to reset the password before connecting the fisrt time.

# Screenshot 

# Steps to reproduce 
1. Try to connect to the VM with SSH
2. Is requiring the password of the azureuser (or rrot) but is not provided in previous steps.

# Expected behavior 
Have the password of the user.

# Current behavior 
We dont have the password when you create the pcs.

# Known workarounds 
Go to the VM blade in Azure portal and reset the password of the user.

# Possible solution 
Go to the VM blade in Azure portal and reset the password of the user.

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by dluc** [comment]
@dotnet007 thanks for the great feedback, we're on it 👍

**Comment by jillcary** [comment]
Thanks for the feedback!

The [Developer Reference Guide](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Reference-Guide) already includes instructions for [SSH into a VM](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Developer-Reference-Guide#ssh-into-a-vm).

I've additionally added an image to more clearly show where in the portal to update the password.

Let us know if these instructions need further improvement, or if they should also be included elsewhere in our documentation.
