### ISSUE TITLE
npm install fails on Windows Subsystem For Linux, Ubuntu 16.04.3 if nodejs-legacy is missing

### ISSUE THREAD

**Issue by holgerkenn** [Azure/azure-iot-pcs-remote-monitoring-dotnet#47]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [X] Improvement

# Description 
npm install fails on package jsonpath@0.2.12

# Screenshot 
npm ERR! jsonpath@0.2.12 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the jsonpath@0.2.12 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.

# Steps to reproduce 
Start WSL Ubuntu Bash on Windows 10
git clone --recursive https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet.git
sudo apt install npm # this pulls node etc. but not nodejs-legacy
cd cli
npm install

# Expected behavior 
npm install succeeds

# Current behavior 
npm install fails

# Known workarounds 
apt install nodejs-legacy

# Possible solution 
Improve documentation

# Context and Environment
* Operating System: WSL (Windows 10 1709), Ubuntu 16.04.3
* GitHub branch: master
* .NET Runtime: ...

**Comment by dluc** [comment]
@holgerkenn just double checking, you managed to solve the problem fixing the npm installation in Windows, correct?

**Comment by mikelid** [comment]
A workaround was posted at https://github.com/LucyBot-Inc/api-spec-converter/issues/132
$sudo npm install -g <<package>> --unsafe-perm=true --allow-root
