### ISSUE TITLE
Dead Documentation Links

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-pcs-remote-monitoring-dotnet#49]
It looks like there are a number of documentation links that appear to go to a private repository.  Please see these documents and update with accessible links:

- https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Architecture#public-facing-services
- https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Public-facing-services

**Comment by ppathan** [comment]
Fixed
