### ISSUE TITLE
Why containers instead of functions?

### ISSUE THREAD

**Issue by MattHoneycutt** [Azure/azure-iot-pcs-remote-monitoring-dotnet#51]
# Type of issue 
- [ ] Bug
- [ ] New feature
- [ X ] Improvement

# Description 
Not really an issue, more of a question: why are the major pieces of this sample implemented using containers instead of as one of the native Azure solutions that already provides the same benefits (scalability, robustness), such as Azure Functions or web apps?  Why self-host everything in VMs?    I'd like to know more about the tradeoffs that were considered and why the solution was implemented as it currently is. 

Thanks!

**Comment by timlaverty** [comment]
Hi Matt,

This is a great question and one we’ve consistently talked about over the course of the release.  The net is that from an Azure perspective we’re happy with however customers want to run their workloads, whether in VMs/containers w/ an orchestrator (Service Fabric, K8s, DC/OS, …), in an app service PaaS environment, using Serverless, Azure Functions, etc.  We have tried to write our microservices so they could be easily hosted in any of them; i.e. the API is always exposed over REST/HTTP.  We felt like Docker containers running on a VM was straight forward and showcased one of those methods.  In the future we will potentially ship deployment support for other alternatives.  One thing that would be useful is to hear from folks like yourself on what we should prioritize – what would you like to see us do?

Thanks, Tim

**Comment by MattHoneycutt** [comment]
Thanks for the feedback.  Personally, I'd like to see implementations using Azure Functions.  It'd also be useful to see where things like Streaming Analytics and Time Series Insights might fit into a solution like this.

**Comment by timlaverty** [comment]
Thanks Matt.  We're laying out our plans for GA and beyond based on the feedback we get from folks like you; you taking the time is appreciated.  

We're looking at ASA and TSI for a future release for rules processing and warm storage.  Az Functions are a potential fit as subcomponents in some microservices (e.g. the device simulation inside of the simulation microservice).

I'm going to leave this Issue open for other folks to comment on as well.

**Comment by hegate** [comment]
Hi @MattHoneycutt .Hector here, one of PMs for PCS. Your feedback is aligned with what we are hearing from various folks. As @timlaverty  mentions, we are in the process of laying out our plans for GA, and we'll make sure to include your comments as feedback for the enhancements.

Thanks again!

**Comment by ToddGomon** [comment]
Add a plus one for me. I agree with Matt, and would like to see more done with native Azure solutions. Why not use Service Fabric and an Asp .Net Core Web App? 
What parts would not work well as Functions and why?

**Comment by dimaing** [comment]
Actually, I like microservices & containers approach. There are several other PCS including the previous version of this one heavily rely on Azure specific implementation. This PCS allows experimenting with Docker Containers microservice architecture within Azure. My vote is to continue with this approach. I'd like to see more stream analytics and BI functionality been developed. Maybe integration of Power BI reports into the dashboard

**Comment by pankajisgarg** [comment]
I would also like microservices hosted in Azure web app as virtual applications, so that
number of different Azure services reduces in system and I can have apt scale out and scale up story.
