### ISSUE TITLE
Error in executing direct methods such as Reboot to a physical device

### ISSUE THREAD

**Issue by faister** [Azure/azure-iot-pcs-remote-monitoring-dotnet#52]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Error in executing direct methods such as Reboot to a physical device, such as one built by following the tutorial at https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-connecting-pi-c.

The same thing goes with trying to change reported property in "physical device".

# Screenshot 
IoTHubClient accepted the message for delivery
Error: Time:Sun Nov 26 22:25:43 2017 File:/build/azure-iot-sdk-c-QvBScE/azure-iot-sdk-c-0.1.0/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteMethod Line:734 Decoding JSON to a multi tree failed
Error: Time:Sun Nov 26 22:25:43 2017 File:/usr/include/azureiot/serializer_devicetwin.h Func:deviceMethodCallback Line:73 failure in EXECUTE_METHOD

# Steps to reproduce 
1. Run sample app on Raspberry Pi, ./sample_app
2. Go to remote monitoring solution portal.
3. Under Devices, select the physical device representing the Raspberry Pi, click Schedule.
4. Select method "Reboot" and click Apply.

# Expected behavior 
1. Direct method returns with message "Rebooting" with status code 201, and the following is displayed on the sample_app console - "Received reboot request"

# Current behavior 
IoTHubClient accepted the message for delivery
Error: Time:Sun Nov 26 22:25:43 2017 File:/build/azure-iot-sdk-c-QvBScE/azure-iot-sdk-c-0.1.0/serializer/src/commanddecoder.c Func:CommandDecoder_ExecuteMethod Line:734 Decoding JSON to a multi tree failed
Error: Time:Sun Nov 26 22:25:43 2017 File:/usr/include/azureiot/serializer_devicetwin.h Func:deviceMethodCallback Line:73 failure in EXECUTE_METHOD

# Known workarounds 
None

# Possible solution 
?

# Context and Environment
* Operating System: Raspberry Pi 3
* GitHub branch: Current main branch
* .NET Runtime: N/A

**Comment by ppathan** [comment]
@jillcary Can you try out the documentation to confirm if it works.

**Comment by asdonald** [comment]
Fixed.
