### ISSUE TITLE
Error example in /scripts/local/.env

### ISSUE THREAD

**Issue by Dolphinsimon** [Azure/azure-iot-pcs-remote-monitoring-dotnet#66]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
There is an error example in the /scripts/local/.env will cause a strange exception when you run the preview5 locally.

**Line 27 (/scripts/local/.env) :** 
_PCS_IOTHUBREACT_HUB_ENDPOINT=Endpoint=sb://iothub-foo-iothub-bar-12345-12345.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=12345=_

**In the telemetry-agent-dotnet releases:**
Line 34 (/scripts/env-vars-setup) :
_e.g. "iothub-ns-aaa-bbb-123456-abcdefghij.servicebus.windows.net"_

**And in telemetry-agent-dotnet project code:**
Line 152~155 （StreamingAgent/Agent.cs) :

```
if (!Uri.TryCreate($"sb://{config.IoTHubConfig.ConnectionConfig.HubEndpoint}/", UriKind.Absolute, out endpoint))
{
throw new InvalidConfigurationException($"Invalid IoTHub endpoint {config.IoTHubConfig.ConnectionConfig.HubEndpoint}");
}

```

The error example will cause the InvalidConfigurationException.
We only need the strings after sb:// (_iothub-ns-aaa-bbb-123456-abcdefghij.servicebus.windows.net_) not the full strings(_Endpoint=sb://iothub-foo-iothub-bar-12345-12345.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=12345=_) copied from Azure Portal.

**Comment by ppathan** [comment]
Thanks for reporting this. Should be fixed by this https://github.com/Azure/telemetry-agent-dotnet/pull/31/files
