### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by rangv** [Azure/azure-iot-pcs-remote-monitoring-dotnet#67]
# Type of issue 
- [ ] Bug
- [x] New Improvement

# Description 
Broken Link: https://github.com/integrations/tower

# Screenshot 

# Steps to reproduce 
1. Click on Tower link

# Expected behavior 

# Current behavior 
Get 404 Error when link is clicked

# Known workarounds 
...

# Possible solution 

https://www.git-tower.com/windows/

**Comment by jillcary** [comment]
Issue was in the wiki documentation under [Local Development Setup](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/wiki/Running-the-Remote-Monitoring-Solution-Locally#local-development-setup).

The link has been updated.
