### ISSUE TITLE
Map API is not getting configured correctly

### ISSUE THREAD

**Issue by pankajisgarg** [Azure/azure-iot-pcs-remote-monitoring-dotnet#76]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
My subscription do not have any usage of Map API but still when i try to kick new deployment I get warning that I will need to fix it manually later. I have tried with two different subscriptions I have.

# Steps to reproduce 
1. Create a solution with a subscription with less than 2 MAP APIs in use.

# Expected behavior 
Solution should get created with Map API enabled.

![image](https://user-images.githubusercontent.com/13584130/38412439-04300b46-39a7-11e8-96e2-1b410f758a94.png)

**Comment by ppathan** [comment]
This is fixed since we moved to Azure Maps
