### ISSUE TITLE
Local deployment - exception raised while loading  Device Model configuration

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-pcs-remote-monitoring-dotnet#82]
# Type of issue 
- [x] Bug
- [ ] New feature
- [ ] Improvement

# Description 
I am trying to perform a local deployment. After several tries and fixes, yesterday, I managed to have all docker processes running (at a Linux ubuntu). But device models could not be established and thus all the devices were off line. 

# Screenshot 
 [ERROR][2018-04-18 11:23:32.305][WebService.1c3774bf-43e1-425f-9700-0457bf32b9b9][DeviceModels:GetList] Unable to load Device Model configuration, {"Message":"Could not find a part of the path '/app/webservice/data/devicemodels/'.","Exception":{"ExceptionFullName":"System.IO.DirectoryNotFoundException","ExceptionMessage":"Could not find a part of the path '/app/webservice/data/devicemodels/'.","StackTrace":"   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)\n   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)\n   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)\n   at System.IO.Directory.GetFiles(String path)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.GetDeviceModelFiles() in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 88\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.GetList() in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 54","Source":"System.IO.FileSystem","Data":{},"InnerException":null}}
devicesimulation_1  | [ERROR][2018-04-18 11:23:32.342][WebService.1c3774bf-43e1-425f-9700-0457bf32b9b9][SimulationRunner:Start] Unexpected error preparing the device model, {"Id":"chiller-01","e":{"ExceptionFullName":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.Exceptions.InvalidConfigurationException","ExceptionMessage":"Unable to load Device Model configuration: Could not find a part of the path '/app/webservice/data/devicemodels/'.","StackTrace":"   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.GetList() in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 66\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.Get(String id) in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 74\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.GetDeviceModel(String id, DeviceModelOverride overrides) in /opt/vsts/work/1/s/SimulationAgent/SimulationRunner.cs:line 293\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.SimulationAgent.SimulationRunner.Start(Simulation simulation) in /opt/vsts/work/1/s/SimulationAgent/SimulationRunner.cs:line 187","Source":"Microsoft.Azure.IoTSolutions.DeviceSimulation.Services","Data":{},"InnerException":{"ExceptionFullName":"System.IO.DirectoryNotFoundException","ExceptionMessage":"Could not find a part of the path '/app/webservice/data/devicemodels/'.","StackTrace":"   at System.IO.UnixFileSystem.FileSystemEnumerable`1.OpenDirectory(String fullPath)\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1.Enumerate()\n   at System.IO.UnixFileSystem.FileSystemEnumerable`1..ctor(String userPath, String searchPattern, SearchOption searchOption, SearchTarget searchTarget, Func`3 translateResult)\n   at System.IO.UnixFileSystem.EnumeratePaths(String path, String searchPattern, SearchOption searchOption, SearchTarget searchTarget)\n   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)\n   at System.IO.Directory.GetFiles(String path)\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.GetDeviceModelFiles() in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 88\n   at Microsoft.Azure.IoTSolutions.DeviceSimulation.Services.DeviceModels.GetList() in /opt/vsts/work/1/s/Services/DeviceModels.cs:line 54","Source":"System.IO.FileSystem","Data":{},"InnerException":null}}}
devicesimulation_1  | [WARN][2018-04-18 11:23:32.343][WebService.1c3774bf-43e1-425f-9700-0457bf32b9b9][DeviceModels:Get] Device model not found, {"id":"chiller-02"}
devicesimulation_1  | [ERROR][2018-04-18 11:23:32.343][WebService.1c3774bf-43e1-425f-9700-0457bf32b9b9][SimulationRunner:Start] The device model doesn't exist, {"Id":"chiller-02"}

# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: Linux Ubuntu
* GitHub branch: ...
* .NET Runtime: ...

**Comment by ppathan** [comment]
Closing issue that were before //build
