### ISSUE TITLE
Local deployment - local_webui exiting - Permission denied

### ISSUE THREAD

**Issue by mtheolog** [Azure/azure-iot-pcs-remote-monitoring-dotnet#83]
# Type of issue 
- [X] Bug
- [ ] New feature
- [ ] Improvement

# Description 
Yesterday, I managed to performed a local deployment (at a Linux Ubuntu) with all pcs up and running. Today I tried to redeploy by following the following: docker-compose down --rmi all and docker-compose up. The webui is exited and the logs refer to lack permissions. 

# Screenshot 
webui_1             | + mkdir -p /app/logs
webui_1             | + nginx -c /app/nginx.conf
webui_1             | nginx: [alert] could not open error log file: open() "/var/lib/nginx/logs/error.log" failed (13: Permission denied)
webui_1             | 2018/04/18 11:23:29 [emerg] 7#7: mkdir() "/var/tmp/nginx/client_body" failed (13: Permission denied)
reverseproxy_1      | + mkdir -p /app/logs
reverseproxy_1      | + nginx -c /app/config/nginx.conf
local_webui_1 exited with code 1
# Steps to reproduce 
1. [First step]
2. [Second step]
3. [and so on...]

# Expected behavior 
...

# Current behavior 
...

# Known workarounds 
...

# Possible solution 
...

# Context and Environment
* Operating System: ...
* GitHub branch: ...
* .NET Runtime: ...

**Comment by ppathan** [comment]
This is should be fixed with latest version. Let us know if not.
