### ISSUE TITLE
How to Run Every Microservices Separately?

### ISSUE THREAD

**Issue by prabhu66** [Azure/azure-iot-pcs-remote-monitoring-dotnet#98]
Hi,

I have to run every microservices in separate port.
Can you please provide me the detail step by steps to run for all microservices in different port. 
Please tell me how to configure Environmental Variables for every microservices in detail.

**Comment by zhang-hua** [comment]
For .Net projects, you need 3 steps:
1. Change the default setting `webservice_port` to use different port. For example, [iothub-manager's port setting](https://github.com/Azure/iothub-manager-dotnet/blob/master/WebService/appsettings.ini#L2).
2. Rebuild the docker image `scripts/docker/build`
3. Change environment variables in docker compose file to use the new port of the services if applied. For example in [local deployment](https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet/blob/master/scripts/local/docker-compose.yml).

**Comment by ppathan** [comment]
Question answered. Closing issue.
